create table todo.user
(
    id bigint generated by default as identity,
    primary key (id)
);

create table todo.task
(
    id      bigint generated by default as identity,
    user_id bigint not null,
    primary key (id),
    constraint fk_task$user_id foreign key (user_id) references todo.user (id)
);

