spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo?currentSchema=todo
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
